### ISSUE TITLE
patch module does not support local files

### ISSUE THREAD

**Issue by rbu** [ansible/ansible-modules-extras#338]
Given the following task:

```
- name: Apply patches
  patch: >
    basedir="/home/user/virtualenv/lib64/python2.7/site-packages/"
    src="patches/some.patch"
    remote_src=False
```

plus an accompanying file in `files/patches/some.patch` in the same role, I get:

```
failed: [remotehost] => {"failed": true}
msg: src patches/some.patch doesn't exist or not readable
```

I ran Ansible through an strace and found it does not even attempt to stat the local file, so this does not look like a typo/configuration error to me.

**Comment by patphobos** [comment]
https://github.com/ansible/ansible-modules-extras/pull/331 should fix this issue. (associated with this https://github.com/ansible/ansible/pull/10507 )

**Comment by rbu** [comment]
Ah, thank you for the pointer. Which of these patches should be necessary to support running with a local file, given I would explicitly specify `remote_src=False`. Judging from the source, I assumed only 84eb895a06c8819ed5d8aea06672a69add2b9d37 (which I can easily apply to a copy of the patch module). But that did not solve the problem.

**Comment by patphobos** [comment]
try https://github.com/renard/ansible/commit/6888f1ccd9a60d656b868317c9fa46e9524bd3f2 associated with https://github.com/ansible/ansible-modules-extras/commit/84eb895a06c8819ed5d8aea06672a69add2b9d37

**Comment by rbu** [comment]
You are right, it works with the full PR applied. Thank you. Should I close the bug or leave it open until the PR is merged?

**Comment by renard** [comment]
@rbu I think you should let the bug open since PR merges often take a looooooong time and the bug is not fixed yet since it PR is not merged.

**Comment by vicendominguez** [comment]
Hey guys! What version will it have this merge? I think that I am suffering this issue in ansible 1.9.0.1. is it possible?

**Comment by bcoca** [comment]
current devel

**Comment by renard** [comment]
Or from the you current git checkout of Ansible you can run:

```
git cherry-pick 6888f1c
cd lib/ansible/modules/extras
git cherry-pick b68c136
git cherry-pick 84eb895
git cherry-pick 08702e4
```

If, like e, you don't want to use the `devel` branch

**Comment by vicendominguez** [comment]
thank you guys.... i am installing it in the boxes via pip.... so, I would be interested about the ETA for that way.

**Comment by bcoca** [comment]
it will be in 1.9.2 or 2.0 which ever happens first, I cannot give you a hard date.

**Comment by vicendominguez** [comment]
thank you very much for the info and for answering :+1:

**Comment by philfry** [comment]
Hi,

the bug is still present in 1.9.2.

Regards

**Comment by ewiger** [comment]
still present in 1.9.1

cheers

**Comment by rbu** [comment]
@ewiger, the PR was merged after 1.9.1 was released. Can you re-check with 1.9.2?

@philfry claims it's also present there, but I haven't checked that version myself yet.

**Comment by rbu** [comment]
I can confirm this issue is still present in 1.9.2. Please reopen.

**Comment by renard** [comment]
indeed it is only fixed in `devel`
You need to cherry-pick both 8a5f162e29f45ce427606706f7e3908ec4ca2bda and 6888f1ccd9a60d656b868317c9fa46e9524bd3f2.

**Comment by mrooney** [comment]
Upgrading to Ansible 1.9.3 resolved this issue for me, thanks!
